lib/doctor_schedule_web/router.ex
defmodule DoctorScheduleWeb.Router do
  use DoctorScheduleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DoctorScheduleWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug DoctorScheduleWeb.Auth.Pipeline
  end

  scope "/", DoctorScheduleWeb do
    pipe_through [:browser, :auth]

    get "/logout", SessionController, :logout
    live "/", PageLive, :index
  end

  scope "/", DoctorScheduleWeb do
    pipe_through :browser

    get "/session", SessionController, :session
    post "/signin", SessionController, :login_create
    post "/signup", SessionController, :create_account
    get "/forgot-password", ForgotPasswordController, :forgot_password
    post "/forgot-password", ForgotPasswordController, :forgot_password_create
  end

  # Other scopes may use custom stacks.
  scope "/api", DoctorScheduleWeb.Api, as: :api do
    pipe_through :api

    post "/password/reset", ResetPasswordController, :create
    post "/password/forgot", PasswordForgotController, :create
    resources "/sessions", SessionController
    resources "/users", UserController, only: [:create]
  end

  scope "/api", DoctorScheduleWeb.Api, as: :api do
    pipe_through [:api, :auth]

    get "/providers/:provider_id/day-availability/:date", ProviderDayAvailabilityController, :show
    get "/providers/:provider_id/month-availability", ProviderMonthAvailabilityController, :show
    resources "/appointments", AppointmentController
    resources "/users", UserController, except: [:create]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # coveralls-ignore-start
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DoctorScheduleWeb.Telemetry
    end
  end

  # coveralls-ignore-stop
end

lib/doctor_schedule/accounts/services/session.ex
defmodule DoctorSchedule.Accounts.Services.Session do
  alias DoctorSchedule.Accounts.Entities.User
  alias DoctorSchedule.Repo

  def authenticate(email, password) do
    case Repo.get_by(User, email: email) do
      nil ->
        {:error, :not_found}

      user ->
        if Argon2.verify_pass(password, user.password_hash) do
          {:ok, user}
        else
          {:error, :unauthorized}
        end
    end
  end
end

lib/doctor_schedule_web/controllers/api/session_controller.ex
defmodule DoctorScheduleWeb.Api.SessionController do
  use DoctorScheduleWeb, :controller
  alias DoctorScheduleWeb.Auth.Guardian

  action_fallback DoctorScheduleWeb.FallbackController

  def create(conn, %{"email" => email, "password" => password}) do
    with {:ok, user, token} <- Guardian.authenticate(email, password) do
      conn
      |> put_status(:created)
      |> render("show.json", %{user: user, token: token})
    end
  end
end

lib/doctor_schedule_web/controllers/session_controller.ex
defmodule DoctorScheduleWeb.SessionController do
  use DoctorScheduleWeb, :controller
  alias DoctorSchedule.Accounts.Entities.User
  alias DoctorSchedule.Accounts.Services.CreateUser
  alias DoctorScheduleWeb.Auth.Guardian

  def session(conn, _params) do
    changeset = User.changeset_login(%User{})
    changeset_insert = User.changeset(%User{})
    session_render(conn, changeset, changeset_insert)
  end

  def login_create(conn, %{"user" => user_params}) do
    Guardian.authenticate(user_params["email"], user_params["password"])
    |> case do
      {:ok, user, _token} ->
        conn
        |> Guardian.Plug.sign_in(user)
        |> put_session(:current_user, user)
        |> put_flash(:info, "Logado com sucesso!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, :unauthorized} ->
        changeset = User.changeset_login(%User{}, user_params)
        changeset = %{changeset | action: :login}
        changeset_insert = User.changeset(%User{})

        conn
        |> put_flash(:error, "Usuario e/ou senha invalido!")
        |> session_render(changeset, changeset_insert)
    end
  end

  def create_account(conn, %{"user" => user_params}) do
    user_params
    |> CreateUser.execute()
    |> case do
      {:ok, _user} ->
        conn
        |> put_flash(:info, "Cadastrado com Sucesso! ")
        |> redirect(to: Routes.session_path(conn, :session))

      {:error, %Ecto.Changeset{} = changeset_insert} ->
        changeset = User.changeset_login(%User{})

        conn
        |> put_flash(:error, "Erro ao cadastrar o usuario!")
        |> session_render(changeset, changeset_insert, true)
    end
  end

  defp session_render(conn, changeset, changeset_insert, sign_up \\ false) do
    render(conn, "session.html",
      changeset: changeset,
      changeset_insert: changeset_insert,
      action: Routes.session_path(conn, :login_create),
      action_insert: Routes.session_path(conn, :create_account),
      sign_up: sign_up
    )
  end

  def logout(conn, _) do
    conn
    |> Guardian.Plug.sign_out()
    |> configure_session(drop: true)
    |> redirect(to: Routes.session_path(conn, :session))
  end
end

lib/doctor_schedule_web/views/session_view.ex
defmodule DoctorScheduleWeb.SessionView do
  use DoctorScheduleWeb, :view
end

lib/doctor_schedule_web/templates/session/login.html.eex
<%= form_for @changeset, @action, [id: "sign-in-form"], fn f -> %>
<h2 class="title">Faca seu login</h2>

<div class="input-field <%= if f.params != %{} && f.source.errors[:email], do: "error" %>">
  <i class="fas fa-envelope <%= f.params != %{} && f.source.errors[:email] && "blur" || "" %>"></i>
  <%= email_input f, :email, placeholder: "E-mail" %>
  <%= error_tag f, :email %>
</div>

<div class="input-field <%= if f.params != %{} && f.source.errors[:password], do: "error" %>">
  <i class="fas fa-lock <%= f.params != %{} && f.source.errors[:password] && "blur" || "" %>"></i>
  <%= password_input f, :password, placeholder: "Senha" %>
  <%= error_tag f, :password %>
</div>

<%= submit "Entrar", class: "btn solid"  %>
<p><%= link "Esqueci a Senha", to: Routes.forgot_password_path(@conn, :forgot_password) %></p>
<% end %>

lib/doctor_schedule_web/templates/session/session.html.eex
<div class="container">
  <div class="forms-container">
    <div class="signin-signup">
      <%= render DoctorScheduleWeb.SessionView, "login.html", assigns %>
      <%= render DoctorScheduleWeb.SessionView, "signup.html", assigns %>
    </div>
  </div>

  <div class="panels-container">
    <div class="panel left-panel">
      <div class="content">
        <h3>Nao tem conta?</h3>
        <p>Basta clicar no botao abaixo</p>
        <button class="btn transparent" id="sign-up-btn">Cadastrar</button>
      </div>
      <img src="<%= Routes.static_path(@conn, "/images/login.svg") %>" alt="Imagem de Medicina" class="img-panel">

    </div>


    <div class="panel right-panel">
      <div class="content">
        <h3>Ja possui conta?</h3>
        <p>Basta clicar no botao abaixo</p>
        <button class="btn transparent" id="sign-in-btn">Logar</button>
      </div>
      <img src="<%= Routes.static_path(@conn, "/images/registry.svg") %>" alt="Imagem de Medicina" class="img-panel">
    </div>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", () => {
    const sign_up_btn = document.querySelector("#sign-up-btn");
    const sign_in_btn = document.querySelector("#sign-in-btn");
    const container = document.querySelector(".container");
    const signup = <%= @sign_up %>
    console.log(signup)
      if (signup) {

        container.classList.add("sign-up-mode")
      }

    sign_up_btn.addEventListener("click", () => {
      container.classList.add("sign-up-mode")
    })

    sign_in_btn.addEventListener("click", () => {
      container.classList.remove("sign-up-mode")
    })
  });
</script>

lib/doctor_schedule_web/templates/session/signup.html.eex
<%= form_for @changeset_insert, @action_insert, [id: "sign-up-form"], fn f -> %>
<h2 class="title">Faca seu Cadastro</h2>

<div class="input-field <%= if f.params != %{} && f.source.errors[:first_name], do: "error" %>">
  <i class="fas fa-user <%= f.params != %{} && f.source.errors[:first_name] && "blur" || "" %>"></i>
  <%= text_input f, :first_name, placeholder: "Nome" %>
  <%= error_tag f, :first_name %>
</div>

<div class="input-field <%= if f.params != %{} && f.source.errors[:last_name], do: "error" %>">
  <i class="fas fa-user <%= f.params != %{} && f.source.errors[:last_name] && "blur" || "" %>"></i>
  <%= text_input f, :last_name, placeholder: "Sobrenome" %>
  <%= error_tag f, :last_name %>
</div>


<div class="input-field <%= if f.params != %{} && f.source.errors[:email], do: "error" %>">
  <i class="fas fa-envelope <%= f.params != %{} && f.source.errors[:email] && "blur" || "" %>"></i>
  <%= email_input f, :email, placeholder: "E-mail" %>
  <%= error_tag f, :email %>
</div>

<div class="input-field <%= if f.params != %{} && f.source.errors[:password], do: "error" %>">
  <i class="fas fa-lock <%= f.params != %{} && f.source.errors[:password] && "blur" || "" %>"></i>
  <%= password_input f, :password, placeholder: "Senha" %>
  <%= error_tag f, :password %>
</div>


<div class="input-field <%= if f.params != %{} && f.source.errors[:password_confirmation], do: "error" %>">
  <i class="fas fa-lock <%= f.params != %{} && f.source.errors[:password_confirmation] && "blur" || "" %>"></i>
  <%= password_input f, :password_confirmation, placeholder: "Confirmar Senha" %>
  <%= error_tag f, :password_confirmation %>
</div>


<%= submit "Cadastrar", class: "btn solid"  %>

<% end %>