lib/doctor_schedule_web/router.ex
defmodule DoctorScheduleWeb.Router do
  use DoctorScheduleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DoctorScheduleWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug DoctorScheduleWeb.Auth.Pipeline
  end

  scope "/", DoctorScheduleWeb do
    pipe_through [:browser, :auth]

    get "/logout", SessionController, :logout
    live "/", PageLive, :index
  end

  scope "/", DoctorScheduleWeb do
    pipe_through :browser

    get "/session", SessionController, :session
    post "/signin", SessionController, :login_create
    post "/signup", SessionController, :create_account
    get "/forgot-password", ForgotPasswordController, :forgot_password
    post "/forgot-password", ForgotPasswordController, :forgot_password_create
  end

  # Other scopes may use custom stacks.
  scope "/api", DoctorScheduleWeb.Api, as: :api do
    pipe_through :api

    post "/password/reset", ResetPasswordController, :create
    post "/password/forgot", PasswordForgotController, :create
    resources "/sessions", SessionController
    resources "/users", UserController, only: [:create]
  end

  scope "/api", DoctorScheduleWeb.Api, as: :api do
    pipe_through [:api, :auth]

    get "/providers/:provider_id/day-availability/:date", ProviderDayAvailabilityController, :show
    get "/providers/:provider_id/month-availability", ProviderMonthAvailabilityController, :show
    resources "/appointments", AppointmentController
    resources "/users", UserController, except: [:create]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # coveralls-ignore-start
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DoctorScheduleWeb.Telemetry
    end
  end

  # coveralls-ignore-stop
end

lib/doctor_schedule_web/templates/page/header.html.leex
<header>
  <div class="header-content">
    <h1>DoctorSchedule</h1>

    <div class="doctor-info">
      <img src="<%= Routes.static_path(DoctorScheduleWeb.Endpoint, "/images/empty_user.png")%>" alt="Dr. Eneias" />
      <div>
        <span>Welcome</span>
        <strong><a href="#"><%= @current_user.first_name %> <%= @current_user.last_name %></a></strong>
      </div>
    </div>

    <%= link to: Routes.session_path(@socket, :logout) do %>
    <i class="fa fa-power-off"></i>
    <% end %>
  </div>
</header>

lib/doctor_schedule_web/templates/page/index.html.leex
<div class="doctor-dashboard">
  <%= live_component @socket, DoctorScheduleWeb.HeaderComponent, assigns %>
  <main>
    <div class="schedule">
      <%= live_component @socket, DoctorScheduleWeb.InfoComponent, assigns %>

      <section class="patients">
        <strong>Morning</strong>
        <%= if @calendar.schedules.morning_appointments == [] do %>
        <p>There is no patients in this period</p>
        <% else %>
        <%= for appointment <- @calendar.schedules.morning_appointments do %>
        <%= live_component @socket, DoctorScheduleWeb.PatientComponent, %{appointment: appointment} %>
        <% end %>
        <% end %>
      </section>

      <section class="patients">
        <strong>Afternoon</strong>
        <%= if @calendar.schedules.afternoon_apointments == [] do %>
        <p>There is no patients in this period</p>
        <% else %>
        <%= for appointment <- @calendar.schedules.afternoon_apointments do %>
        <%= live_component @socket, DoctorScheduleWeb.PatientComponent,  %{appointment: appointment} %>
        <% end %>
        <% end %>
      </section>
    </div>

    <aside>
      <%= live_component @socket, DoctorScheduleWeb.ScheduleComponent, calendar: @calendar %>
    </aside>
  </main>
</div>

lib/doctor_schedule_web/templates/page/info.html.leex
<h1>Consultancies scheduleed</h1>
<p>
  <%= if @calendar.is_today do %>
  <span>Today | </span>
  <% end %>
  <span>Day <%= @calendar.current_date.day %> | </span>
  <span><%= @calendar.current_date |> Timex.weekday |> Timex.day_name %></span>
</p>
<%= if @calendar.next_one != nil do %>
<div class="next-apointment">
  <strong>Next Patient</strong>
  <div>
    <img src="<%= Routes.static_path(DoctorScheduleWeb.Endpoint, "/images/empty_user.png")%>" alt="<%= @calendar.next_one.user.first_name %>" />
    <strong><%= @calendar.next_one.user.first_name %> <%= @calendar.next_one.user.first_name %></strong>
    <span>
      <i class="fa fa-clock-o" aria-hidden="true"></i>
      <%= @calendar.next_one.date.hour %>:00
    </span>
  </div>
</div>
<% end %>

lib/doctor_schedule_web/templates/page/patient.html.leex
  <div class="patient">
    <span>
      <i class="fa fa-clock-o"></i>
      <%= @appointment.date.hour %>:00
    </span>

    <div class="patient-info">
      <img src="<%= Routes.static_path(DoctorScheduleWeb.Endpoint, "/images/empty_user.png")%>"
        alt="<%= @appointment.user.first_name %>" />
      <strong><%= @appointment.user.first_name %> <%= @appointment.user.last_name %></strong>
    </div>
  </div>

lib/doctor_schedule_web/templates/page/schedule.html.leex
 <div class="calendar">
   <div class="month">
     <ul>
       <li class="prev">
         <a href="#" phx-click="previous-month">
           <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
         </a>
       </li>
       <li> <%= @calendar.current_month %></li>
       <li class="next">
         <a href="#" phx-click="next-month">
           <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
         </a>
       </li>
     </ul>
   </div>

   <ul class="weekdays">
     <%= for day_of_week <- @calendar.days_of_week do %>
     <li><%= day_of_week %> </li>
     <% end %>
   </ul>

   <ul class="days">
     <%= for date_info <- @calendar.days do %>
     <li class="<%= date_info.type %> " phx-click="pick-date" phx-value-date="<%= date_info.date %>"><%= date_info.date.day %> </li>
     <% end %>
   </ul>
 </div>